name: Build and Deploy Documents
on:
  push:
    branches:
      - v2
      
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - run: npm install
    - run: npm run build

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./typedoc

    - name: 📦 publish to NPM
      uses: kktjs/npm-publish@main
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./package.json
        tag: next